/* Database schema to keep the structure of entire database. */
CREATE TABLE animals(
 id INT,
 name VARCHAR(40),
	date_of_birth DATE,
	escape_attempts INT,
	neutered BOOLEAN, 
	weight_kg Decimal,
	PRIMARY KEY (id)
);

ALTER TABLE animals ADD species VARCHAR(45);


/** create owners table */
CREATE TABLE owners (id INT GENERATED ALWAYS AS IDENTITY,
					full_name VARCHAR(255) NOT NULL,age INT,
                    CONSTRAINT pk_owners PRIMARY KEY(id)
					)


/** create species table */
CREATE TABLE species (id INT GENERATED ALWAYS AS IDENTITY,
					 name VARCHAR(45), CONSTRAINT pk_species PRIMARY KEY(id))
/** make id auto incremated  */
		 
ALTER  TABLE animals ALTER COLUMN id SET  GENERATED BY DEFAULT;	

/** drop species column */
ALTER TABLE animals DROP COLUMN species; 

/** add species_id foreign key */
ALTER TABLE animals ADD species_id INT, 
ADD CONSTRAINT fk_species FOREIGN KEY(species_id) REFERENCES species(id);

/** add owner_id foreign key */
ALTER TABLE animals ADD owner_id INT, 
ADD CONSTRAINT fk_owners FOREIGN KEY(owner_id) REFERENCES owners(id);

/** many to mnay relationship implementation */
/* --create vets table */
 CREATE TABLE vets (
      id INT GENERATED ALWAYS AS IDENTITY,
 	  name VARCHAR(255),
	  age INT,
	  date_of_graduation DATE,
	  CONSTRAINT pk_vets PRIMARY KEY(id)
  )
  /** --- create specializations table to handle relationship between vet and species */

CREATE TABLE specializations (
 vet_id INT, species_id INT,
CONSTRAINT pk_specializations PRIMARY KEY(vet_id,species_id),
CONSTRAINT fk_vets FOREIGN KEY(vet_id) REFERENCES vets(id),
CONSTRAINT fk_species FOREIGN KEY(species_id) REFERENCES species(id));
	/* -- create visits table to handle relationship between vets and animals */

CREATE TABLE visits (
animal_id INT, vet_id INT,
date_of_visit DATE,
CONSTRAINT fk_animals FOREIGN KEY(animal_id) REFERENCES animals(id),
CONSTRAINT fk_vets FOREIGN KEY(vet_id) REFERENCES vets(id));


/* ALter table owners */
ALTER TABLE owners ADD COLUMN email VARCHAR(120);
	